#!/bin/bash

set -e

if [ "x$1" = "x" ]; then
    echo "Syntax: $0 [-f] image ..."
    echo ""
    echo "  -f   force re-build by not using cache"
    echo ""
    exit 1
fi

build_opts=""
force=0
if [ "x$1" = "x-f" ]; then
    force=1
    build_opts+=" --no-cache=true"
    shift
fi

if [ $(id -u) -ne 0 ]; then
    sudo="sudo"
fi

git pull

for this in $*; do
    dir=$(echo ${this} | awk -F : '{print $1}')
    test -d ${dir} || echo "Error: ${image} (subdirectory $dir) not found"
    test -d ${dir} || exit 1
done

for this in $*; do
    image=$(echo $this | sed -e 's!/*$!!')    # remove trailing slashes
    dir=$(echo ${image} | awk -F : '{print $1}')
    if [ $force -eq 1 ]; then
	${sudo} docker rmi "eduid/${image}" "docker.sunet.se/eduid/${image}" || true
    fi
    ${sudo} docker build $build_opts --force-rm=true -t="eduid/${image}" "${dir}"
    ${sudo} docker tag -f "eduid/${image}" "docker.sunet.se/eduid/${image}"
done
