#!/bin/bash

set -e

if [ "x$1" = "x" ]; then
    echo "Syntax: $0 image ..."
    exit 1
fi

if [ $(id -u) -ne 0 ]; then
    sudo="sudo"
fi

git pull

for this in $*; do
    dir=$(echo ${this} | awk -F : '{print $1}')
    test -d ${dir} || echo "Error: ${image} (subdirectory $dir) not found"
    test -d ${dir} || exit 1
done

for this in $*; do
    image=$(echo $this | sed -e 's!/*$!!')    # remove trailing slashes
    dir=$(echo ${image} | awk -F : '{print $1}')
    ${sudo} docker build --force-rm=true -t="eduid/${image}" "${dir}"
    ${sudo} docker tag -f "eduid/${image}" "docker.sunet.se/eduid/${image}"
done
