#!/bin/bash

set -e

. ./common.sh

if [ "x$1" = "x" ]; then
    echo "Syntax: $0 image ..."
    exit 1
fi

sudo=$(get_docker_sudo_command)

check_is_subdirs $*

for this in $*; do
    base=$(get_docker_image_base)
    image=$(echo $this | sed -e 's!/*$!!')    # remove trailing slashes
    for ver in 'latest' 'stable'; do
	echo "Pulling ${base}/${image}:${ver}"
	${sudo} docker pull "${base}/${image}:${ver}" || true
    done
done
