#!/bin/bash

set -e

. ./common.sh

if [ "x$1" = "x" ]; then
    echo "Syntax: $0 image ..."
    exit 1
fi

sudo=$(get_docker_sudo_command)

check_is_subdirs $*

for this in $*; do
    ver='latest'
    base=$(get_repository_image_base)
    image=$(echo $this | sed -e 's!/*$!!')    # remove trailing slashes
    dir=$(echo ${image} | awk -F : '{print $1}')
    test -f ${dir}/metadata.sh && . ${dir}/metadata.sh

    if [ -d "${dir}/${ver}" ]; then
	dir="${dir}/${ver}"
	test -f ${dir}/metadata.sh && . ${dir}/metadata.sh
    fi

    image=$(echo $this | sed -e 's!/*$!!')    # remove trailing slashes
    ${sudo} docker push "${base}/${image}:${ver}"
done
